import { Project } from "./types";

export const projects: Project[] = [
  {
    title: "Zacode Artikel",
    src: "10.png",
    color: "#ddd6fe",
    url: "https://zacode.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Tokopedia Clone – Mobile & Backend",
    src: "tokped.png",
    color: "#dbeafe",
    url: "https://www.youtube.com/live/DsuZHUebC5g?si=6x54kzwJZBw4R3na",
    role: "Fullstack Developer",
  },
  {
    title: "Zacode Template Fullstack – VS Code Extension",
    src: "exten.png",
    color: "#ddd6fe",
    url: "https://marketplace.visualstudio.com/items?itemName=Sanjaee.zacode-clone-extension",
    role: "Fullstack Developer",
  },
  {
    title: "Zadonate – Donation Platform",
    src: "donate.png",
    color: "#fee2e2",
    url: "https://www.tiktok.com/@ahmadafriza25/video/7586206227193941264",
    role: "Fullstack Developer",
  },
  {
    title: "Hackathon Kolosal – Real-time Video Conferencing with AI",
    src: "zoom.png",
    color: "#dbeafe",
    url: "https://youtu.be/HatAyNk_TYQ?si=Mrod15lKyNgszMts",
    role: "Fullstack Developer",
  },
  {
    title: "Gojek Clone – Microservices Mobile App",
    src: "1.png",
    color: "#dbeafe",
    url: "https://github.com/Sanjaee/Mobile-Helper.git",
    role: "Fullstack Developer",
  },
  {
    title: "E-Wallet Application – Payment Gateway Integration",
    src: "walet.png",
    color: "#fae8ff",
    url: "https://www.tiktok.com/@ahmadafriza25/video/7509819404872420614",
    role: "Fullstack Developer",
  },
  {
    title: "Tokopedia Clone",
    src: "1.png",
    color: "#dbeafe",
    url: "https://ui-tokopedia.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Authentication OTP",
    src: "9.png",
    color: "#fae8ff",
    url: "https://frontend-otp-tau.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Cod Yuk",
    src: "4.png",
    color: "#ddd6fe",
    url: "https://cod-yuk.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Rentals House",
    src: "3.png",
    color: "#fae8ff",
    url: "https://web-kontrakan.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Dashboard Zakat",
    src: "5.png",
    color: "#fee2e2",
    url: "https://data-zakat.vercel.app",
    role: "Fullstack Developer",
  },
  {
    title: "Social Media App",
    src: "7.png",
    color: "#dbeafe",
    url: "https://websocialmedia.vercel.app/page.html",
    role: "Fullstack Developer",
  },
  {
    title: "Takapedia Clone",
    src: "8.png",
    color: "#ddd6fe",
    url: "https://taka-clone-ez4.vercel.app",
    role: "Fullstack Developer",
  },
];
